name: Build and Publish Electron Launcher

on:
  push:
    branches: [main]
  release:
    types: [published]

jobs:
  build:
    runs-on: windows-latest

    steps:
      # Récupérer le code du repo
      - uses: actions/checkout@v4

      # Installer Node.js
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      # Installer les dépendances
      - name: Install dependencies
        run: npm install

      # Build et publication avec Electron Builder
      - name: Build and Publish
        run: npm run build && npx electron-builder --publish always
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}